deps/build.jl
deps/llvm-extra/Makefile
deps/llvm-extra/Target/NVPTX.cpp
src/api.jl

I'm starting to hate all this dynamic library stuff. Wasn't macOS supposed to fix this? On Linux we could use `dlmopen`, but that's not portable...

Try to fix shlib loading on mac

---

REQUIRE
lib/3.9/libLLVM_common.jl
lib/4.0/libLLVM_common.jl
lib/libLLVM_extra.jl
src/core.jl
src/core/attributes.jl
src/core/metadata.jl
src/core/type.jl
src/core/value/constant.jl
src/pass.jl
src/passmanager.jl
src/types.jl
src/util.jl

0.6 syntax deprecation fixes

---

.travis.yml
docs/src/index.md
src/LLVM.jl
src/base.jl
src/core/function.jl
src/init.jl
test/documentation.jl
test/runtests.jl
test/util.jl

Similar to JuliaGPU/CUDAdrv.jl#49

Support for loading/testing the package if the build failed.

---

COVERAGE.md
src/core/value/constant.jl
src/irbuilder.jl
test/core.jl
test/irbuilder.jl

Cover most of irbuilder.

---

src/core.jl
src/core/instructions.jl
src/core/value/constant.jl
test/irbuilder.jl

Necessary for JuliaGPU/CUDAnative.jl#84

Allow alignment calls on instructions.

---

src/core.jl
src/core/basicblock.jl
src/core/function.jl
src/core/instructions.jl
src/core/module.jl
src/core/type.jl
src/core/value.jl
src/core/value/constant.jl
src/core/value/user.jl
src/datalayout.jl
src/types.jl
test/irbuilder.jl

Reduce forward declarations

---

COVERAGE.md
src/execution.jl
test/execution.jl

Not sure if the whole `ExecutionEngineFunctionSet` is a good idea...

wrap LLVMAddModule, LLVMRemoveModule, LLVMFindFunction

---

src/execution.jl

Looks like FemtoCleaner didn't update after the PR got merged.

fix immutable deprecation

---

examples/Kaleidoscope/README.md

fix typo in Kaliedoscope README

---

docs/make.jl
docs/src/lib/interop.md
src/LLVM.jl
src/interop.jl
src/interop/asmcall.jl
src/interop/base.jl
test/interop.jl
test/runtests.jl

@vchuravy Something else you want in there?

Initial Julia/LLVM interop submodule.

---

src/interop/asmcall.jl

Doesn't work properly together with precompilation.

Use symbols instead of a global buffer for at-asmcall.

---

Project.toml
deps/build.jl
src/LLVM.jl

Fixes https://github.com/maleadt/LLVM.jl/issues/115 and https://github.com/JuliaGPU/CUDAnative.jl/issues/245

Detect LLVM by looking at Libdl.dllist.

---

src/core/value/user.jl

Restrict getindex signature.

---

lib/libLLVM_extra.jl
src/core/basicblock.jl
src/core/function.jl
src/core/module.jl
test/core.jl

Prevents having to iterate values if size is unknown.

Specialized isempty functions.

---

src/core/instructions.jl
src/interop.jl
src/interop/passes.jl
test/core.jl
test/interop.jl

Add high-level wrappers for the Julia passes.

---

.appveyor.yml
.gitlab-ci.yml
.travis.yml
lib/8.0/libLLVM_common.jl
lib/libLLVM_extra.jl
src/core/instructions.jl
src/core/metadata.jl
src/core/module.jl
src/core/value/constant.jl
src/debuginfo.jl
src/pass.jl
src/passmanager.jl
test/core.jl
test/debuginfo.jl
test/transform.jl

https://github.com/maleadt/LLVM.jl/pull/146 got closed and broken because the base branch was deleted by bors...

Metadata and get/set subprogram

---

src/LLVM.jl

ref https://github.com/JuliaLang/julia/pull/32651

Fix compilecache-like functionality on 1.3

---

.gitlab-ci.yml
src/pass.jl
test/pass.jl

Fixes https://github.com/maleadt/LLVM.jl/issues/164

Remove BBpass

---

.gitlab-ci.yml
src/transform.jl
test/transform.jl

Adapts to https://github.com/JuliaLang/julia/pull/34313, fixes https://github.com/maleadt/LLVM.jl/issues/166

Updates for Julia

---

src/core/function.jl
src/core/instructions.jl
src/core/type.jl
src/core/value/user.jl
test/core.jl
test/execution.jl

Would have caught the CUDAnative/GPUCompiler segfault fixed in https://github.com/JuliaGPU/GPUCompiler.jl/pull/24

Add bounds checking to iterators.

---

src/interop.jl
src/interop/pointer.jl
test/interop.jl

Ref https://github.com/JuliaLang/julia/pull/36059

Add Julia pointer intrinsics.

---

examples/constrained.jl
examples/generated.jl
examples/sum_integrated.jl
src/bitcode.jl
src/deprecated.jl
src/interop/asmcall.jl
src/interop/base.jl
src/interop/pointer.jl
test/bitcode.jl
test/interop.jl

https://github.com/JuliaLang/julia/pull/36576

Adapt to simplified llvmcall.

---

lib/libLLVM_extra.jl
src/pass.jl
src/passmanager.jl

https://github.com/JuliaLang/julia/pull/37298

Adapt to new LLVM pass API in Julia.

---

src/core/value/constant.jl
test/core.jl

Also improves `ConstantFP` in the process.

Added methods for ConstantArray

---

.github/workflows/ci.yml
src/LLVM.jl

Ref https://github.com/JuliaLang/julia/pull/38306

Adapt to renamed libllvm getter.

---

src/core/instructions.jl
test/core.jl

Ref https://github.com/JuliaLang/julia/pull/38977

Update opcodes, support Freeze.

---

lib/11/libLLVM_h.jl
lib/12/libLLVM_h.jl
res/missing_defs.jl

Add the definition of `off_t` for Apple Silicon

---

docs/src/lib/interop.md
examples/constrained.jl
examples/generated.jl
examples/sum_integrated.jl
src/core/module.jl
src/deprecated.jl
src/interop/asmcall.jl
src/interop/base.jl
src/interop/pointer.jl
src/transform.jl
test/interop.jl

Now seems to be the time to do a bunch of those.
@jpsamaroo @vchuravy any breaking changes you guys need or want?

Breaking changes

---

lib/libLLVM_extra.jl

https://github.com/maleadt/LLVM.jl/pull/238#issuecomment-871484619

Fix the LLVMExtra_jll ccall invocations.

---

.github/workflows/ci.yml
Project.toml
deps/LLVMExtra/CMakeLists.txt
deps/LLVMExtra/COPYRIGHT
deps/LLVMExtra/LICENSE-APACHE
deps/LLVMExtra/LICENSE-MIT
deps/LLVMExtra/README.md
deps/LLVMExtra/include/LLJIT.h
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/include/Orc.h
deps/LLVMExtra/lib/CMakeLists.txt
deps/LLVMExtra/lib/llvm-api.cpp
deps/LLVMExtra/lib/orc.cpp
deps/build_local.jl
test/Project.toml
test/runtests.jl

- import LLVMExtra
- add a build_local.jl

Import LLVMExtra

---

Project.toml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/attributes.jl
src/core/function.jl
test/core.jl

- backport TypeAttribute wrappers
- add TypeAttribute

Add backport of TypeAttribute

---

.github/workflows/ci.yml
Manifest.toml

Fixes https://github.com/maleadt/LLVM.jl/issues/291.

Bump LLVMExtra for 1.9 compat.

---

.github/workflows/ci.yml
lib/11/libLLVM_h.jl
lib/12/libLLVM_h.jl
lib/13/libLLVM_h.jl
src/LLVM.jl
src/init.jl
src/version.jl

Should fix https://github.com/maleadt/LLVM.jl/issues/290
cc @max-Hawkins

Rework initialization

---

src/LLVM.jl
src/version.jl

Makes it possible to load it from a different location.

Don't hard-code path to libLLVM.

---

test/interop.jl

llvmcall on 1.9 refuses these invocations.
Should fix CI on nightly.

Remove test calling intrinsic with invalid arguments.

---

src/core/metadata.jl
test/core.jl

Fixes https://github.com/maleadt/LLVM.jl/issues/306

Support null metadata, represent as nothing.

---

Manifest.toml
Project.toml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/module.jl
src/core/type.jl
src/core/value/constant.jl
test/core.jl

Now including a breaking release bump, sadly.

Reland ConstantArray changes

---

src/interop/asmcall.jl
test/interop.jl

Fixes https://github.com/maleadt/LLVM.jl/issues/325

Fix asmcall macro hygiene.

---

src/core/basicblock.jl
test/core.jl

Namely predecessors/successors.

Add some simple CFG queries

---

test/orcv2.jl

Not sure how this ever worked on our nightly tests...

Fix ORCv2 test.

---

Manifest.toml
Project.toml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
lib/libLLVM_julia.jl
src/LLVM.jl
src/executionengine/lljit.jl
src/orcv2.jl
test/jljit.jl
test/runtests.jl

Partner PR to https://github.com/JuliaLang/julia/pull/49858.

Add Interface to julia OJIT

---

src/core/context.jl
src/interop/pointer.jl
test/core_tests.jl
test/instructions_tests.jl
test/interop_tests.jl

Together with https://github.com/JuliaLang/julia/pull/49846, this makes it possible to enable opaque pointers for a context.

Support enabling opaque pointers.

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/context.jl

The API for that is only available on LLVM 15...

Don't check whether opaque pointers had been configured.

---

.github/download_build.sh
.github/workflows/ci.yml

... instead of building it ourselves. This is much faster.

Download asserts builds from Buildkite.

---

.github/workflows/ci.yml
src/interop/pointer.jl

Initial adaption to https://github.com/JuliaLang/julia/pull/53687

Adapt to pointer types.

---

src/core/context.jl

Avoids the hang in https://github.com/JuliaGPU/GPUCompiler.jl/pull/557#issuecomment-2066983352

Don't install handle_error during precompilation

---

.github/workflows/ci.yml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/Core.cpp
examples/sum_orc.jl
lib/13/libLLVM_extra.jl
lib/14/libLLVM_extra.jl
lib/15/libLLVM_extra.jl
lib/16/libLLVM_extra.jl
lib/17/libLLVM_extra.jl
src/core/metadata.jl
test/runtests.jl

Work around https://github.com/maleadt/LLVM.jl/issues/417, ignore https://github.com/maleadt/LLVM.jl/issues/405.

Make CI green

---

deps/LLVMExtra/lib/Core.cpp

Fixes building on older Julia versions.

Add include guards

---

Project.toml

Bump minor version, since there was a Julia bump to 1.10

Bump to 8.1.0

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/Core.cpp
lib/15/libLLVM_extra.jl
lib/16/libLLVM_extra.jl
lib/17/libLLVM_extra.jl
lib/18/libLLVM_extra.jl

x-ref https://github.com/llvm/llvm-project/pull/99087

Switch context getters to upstream API.

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/Core.cpp
lib/15/libLLVM_extra.jl
lib/16/libLLVM_extra.jl
lib/17/libLLVM_extra.jl
lib/18/libLLVM_extra.jl
src/LLVM.jl
src/core/metadata.jl
src/deprecated.jl
test/core_tests.jl

x-ref https://github.com/llvm/llvm-project/pull/104786/files#r1721883459

Switch to existing upstream APIs for GlobalObject metadata handling.

---

lib/15/libLLVM.jl
lib/16/libLLVM.jl
lib/17/libLLVM.jl
lib/18/libLLVM.jl
res/llvm.toml

Rebase of https://github.com/maleadt/LLVM.jl/pull/256

Add Doxygen comments to the API wrappers.

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/Core.cpp
src/core/function.jl
src/core/value/constant.jl

https://github.com/llvm/llvm-project/pull/105521

Switch initializer and personality clear APIs to upstream version.

---

src/newpm.jl

Closes https://github.com/maleadt/LLVM.jl/issues/487

Don't error on empty pass managers.

---

ext/BFloat16sExt.jl
test/core_tests.jl

Also adds tests to catch if they ever regress.

Fix BFloat16 extension

---

docs/src/lib/instructions.md
docs/src/man/instructions.md
src/core/instructions.jl
src/newpm.jl
src/utils.jl
test/instructions_tests.jl

Add atomic inst ops

---

src/interop/passes.jl
test/newpm_tests.jl

Got deleted in JuliaLang/julia#57308

version bound LowerExcHandlersPass

---

Project.toml

Add compat for `BFloat16s.jl` v0.6.0
