.travis.yml
deps/build.jl
deps/llvm-extra/Makefile

This fixes some issues but I'm still not there. With this I get
```
c++ -I/Users/andreasnoack/juliagpu/usr/include -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wnon-virtual-dtor -Werror=date-time -std=c++11 -O3 -DNDEBUG -fno-exceptions -fno-rtti -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -fno-rtti -DJULIA_ENABLE_THREADING=1 -fPIC -DJULIA_INIT_DIR=\"/Users/andreasnoack/juliagpu/usr/lib\" -I/Users/andreasnoack/juliagpu/usr/include/julia -fPIC -I/Users/andreasnoack/juliagpu/usr/include   -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_NVPTX -DTARGET_X86 -D_GLIBCXX_USE_CXX11_ABI=0 -L/Users/andreasnoack/juliagpu/usr/lib …
```

Fix build on Mac

---

.travis.yml
deps/llvm-extra/Makefile
deps/llvm-extra/Target/NVPTX.cpp
lib/4.0/libLLVM_common.jl
lib/4.0/libLLVM_h.jl
src/core/value/constant.jl
src/transform.jl
test/transform.jl

4.0 has branched, so let's make LLVM.jl fully compatible. This also riles in some upcoming changes for 4.0+ (deprecating the NVVM initializer).

Support for LLVM 4.0+

---

deps/llvm-extra/IR/Value.cpp
lib/libLLVM_extra.jl
src/core/value.jl
test/core.jl

Missing from C API, so add to `llvm-extra`.

Add context getter for Values

---

REQUIRE
src/core/instructions.jl
test/execution.jl

For `args` we don't want `Value` in an `invariant` (?) position because if we end up with a Vector that has more specific types than `Value` e.g. `Instruction`, this function couldn't be called.
Also, the results of `zip(args...)` is two tuples but we need arrays to get the `Ptr`, therefore collect the result. In addition, the length should be given as a `UInt32`.
Added a test as well which should cover these lines (it seems they were not previously tested). Found this when working on Kaleidoscope.jl when the if statements are introduced.

fix arg type and API call for LLVMAddIncoming

---

src/core/value/constant.jl

Without this, tests fail, often with "ERROR: LoadError: bitcast: argument size does not match size of target type".

Fixes tests on 32-bit Julia

---

src/interop/asmcall.jl
test/interop.jl

Allows to return a tuple.
cc @jiahao

asmcall: specify return type as an expression.

---

src/core/module.jl
test/core.jl

Much cleaner than `push!`. Multi-arg setindex is a little funky though.

Use setindex for setting module flags.

---

.gitlab-ci.yml
lib/9.0/libLLVM_common.jl
lib/9.0/libLLVM_h.jl

```diff
+function LLVMAddAddDiscriminatorsPass(PM)
+function LLVMAddGlobalIFunc(M, Name, NameLen, Ty, AddrSpace, Resolver)
+function LLVMAppendExistingBasicBlock(Fn, BB)
+function LLVMBinaryCopyMemoryBuffer(BR)
+function LLVMBinaryGetType(BR)
+function LLVMBuilderGetDefaultFPMathTag(Builder)
+function LLVMBuilderSetDefaultFPMathTag(Builder, FPMathTag)
+function LLVMCreateBinary(MemBuf, Context, ErrorMessage)
+function LLVMDIBuilderCreateEnumerator(Builder, Name, NameLen, Value, IsUnsigned)
+function LLVMDIFileGetDirectory(File, Len)
+function LLVMDIFileGetFilename(File, Len)
+function LLVMDIFileGetSource(File, Len)
+function LLVMDIGlobalVariableExpressionGetExpression(GVE)
+function LLVMDIGlobalVariableExpressionGetVariable(GVE)
+function LLVMDILocationGetInlinedAt(Location)
+function …
```

Add wrappers for LLVM 9.0 (rc5).

---

src/LLVM.jl

It confuses code loading when running under coverage.

Don't add an include dependency on a directory.

---

test/interop.jl

Fixes https://github.com/maleadt/LLVM.jl/issues/158

Don't unconditionally run x86-specific tests.

---

src/interop/base.jl
test/core.jl

Ref https://github.com/JuliaLang/julia/pull/25984

Deal with changed runtime function.

---

lib/libLLVM_extra.jl
lib/libLLVM_h.jl
src/LLVM.jl
src/base.jl
src/init.jl
src/util.jl
test/transform.jl

This partially walks back https://github.com/maleadt/LLVM.jl/pull/188/files because (1) we really are incompatible with external copies of LLVM (because of the extra API calls we compile into Julia and thus always call Julia's libLLVM) and (2) there was some fragility with broken user set-ups as noticed in https://github.com/JuliaGPU/CUDA.jl/issues/249.
However, I made sure to keep the change that makes LLVM precompilable without knowledge about LLVM, so @DhairyaLGandhi this should still work with Heroku (where the location of `libLLVM` changes between precompilation and run-time, which resulted in an invalid cached `libllvm` path). Could you verify?

Go back to inspecting Libdl.dllist to find LLVM.

---

src/core/function.jl
src/deprecated.jl
src/util.jl
test/core.jl

Fixed https://github.com/maleadt/LLVM.jl/issues/112
```julia
julia> using LLVM
julia> intr = Intrinsic("llvm.sin")
Intrinsic(211): "llvm.sin" (overloaded)
julia> name(intr)
"llvm.sin"
julia> isoverloaded(intr)
true
julia> name(intr, [LLVM.DoubleType()])
"llvm.sin.f64"
julia> FunctionType(intr, [LLVM.DoubleType()])
double (double)
julia> typeof(ans)
FunctionType
julia> mod = LLVM.Module("")
julia> LLVM.Function(mod, intr, [LLVM.DoubleType()])
; Function Attrs: nounwind readnone speculatable
declare double @llvm.sin.f64(double) #0
julia> typeof(ans)
LLVM.Function
julia> f = first(functions(mod))
; Function Attrs: nounwind readnone speculatable
declare double @llvm.sin.f64(double) #0
julia> isintrinsic(f)
true
julia> Intrinsic(f)
Intrinsic(211): "llvm.sin" (overloaded)
```
TODO: better …

Wrap intrinsics API.

---

src/core/metadata.jl
src/core/module.jl
src/datalayout.jl
src/interop/base.jl
src/ir.jl
test/core.jl
test/datalayout.jl
test/ir.jl

This seems like a better (more common) way to do this. Also brings down invalidations from ~400 to 0 :-)

Implement Base.string instead of convert(::String).

---

src/LLVM.jl

Fixes https://github.com/maleadt/LLVM.jl/issues/209 using https://github.com/JuliaLang/julia/pull/38172.

Use jl_get_libllvm to locate libLLVM.

---

COVERAGE.md
src/core/module.jl
src/core/type.jl
src/core/value/constant.jl
test/core.jl

This PR adds some convenient constructors for `ConstantStruct` and allows for multidimensional `ConstantArray`'s.
Nested structs are currently not supported via the `ConstantStruct(value, packed::Core.Bool=false)`, `ConstantStruct(value, ctx::Context, packed::Core.Bool=false)` and `ConstantStruct(value, typ::LLVMType)` constructors. After some testing and looking at the generated LLVM IR of some C code using nested structs, it appears like nested structs need to be named. This is an issue because we can't know the LLVM name of a nested struct type via a Julia value. Of course we could define our own LLVM struct types for nested structs, but this leads to other issues, like making sure the names do not clash, and duplicated definitions of the same struct (e.g. when calling `ConstStruct` …

Constructors for ConstantStruct and multidimensional ConstantArrays

---

COVERAGE.md
src/orc.jl
src/support.jl
test/orc.jl

After spending quite a bit of time debugging the wrong part of the compiler I realized that
I was jumping on a non-executable page..., which was apparently due to the fact that I had
an unresolved symbol and OrcJIT decided not to tell me.

[ORC] Implement a reasonable default resolver and throw errors on undefinded symbols

---

test/transform.jl

Tested on https://github.com/JuliaLang/julia/pull/40774.
https://releases.llvm.org/12.0.0/docs/ReleaseNotes.html:
> The ConstantPropagation pass was removed. Users should use the InstSimplify pass instead.

Compatibility with LLVM 12.

---

.github/workflows/ci.yml
Manifest.toml
Project.toml
lib/libLLVM_extra.jl
lib/libLLVM_julia.jl
src/LLVM.jl
src/transform.jl
test/transform.jl

@maleadt I think we can't maintain support for Julia before 1.6 with this.
LLVMExtra_jll declares a minimum compat of 1.6

Use LLVMExtra_jll

---

.github/workflows/ci.yml
Manifest.toml
Project.toml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
examples/constrained.jl
lib/11/libLLVM_h.jl
lib/12/libLLVM_h.jl
lib/libLLVM_extra.jl
src/core/instructions.jl
src/core/metadata.jl
src/core/module.jl
src/debuginfo.jl
src/dibuilder.jl
src/interop/utils.jl
test/core.jl

Because **somebody** removed the `LLVMGetSourceLocation` API we had hacked in Julia, I decided to properly flesh out our coverage of the (read only) parts of the Metadata API.
Breaking changes:
- metadata is now represented as `Metadata` nodes in LLVM, and not directly as `MetadataAsValue` wrappers. That means metadata isn't a value anymore, so you'll need to add `Value(...)` calls where you actually need a value instead of raw metadata.
- named module metadata iteration has been reworked to more closely match the LLVM APIs. Essentially, you need to fetch the metadata using `metadata(mod)[...]`, and then `push!(...)` to append metadata nodes.

Improve coverage of Metadata API

---

Manifest.toml
Project.toml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/transform.jl
test/transform.jl

This is needed to fully copy Base's optimization pipeline on LLVM 12. And it turns out to be actually needed to avoid certain local memory allocations with CUDA.jl.

Add support for CFG simplification with options.

---

src/core/function.jl
src/core/instructions.jl
src/core/value/user.jl

Simplifies the implementation by reusing the AbstractArray implementation. Also gives us some functionality for free, like `parameters(...)[end]`, or getindex with ranges, etc without requiring `collect` everywhere.

Make some iterators a subtype of AbstractVector.

---

Manifest.toml
Project.toml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/instructions.jl
src/irbuilder.jl
test/instructions.jl
test/runtests.jl

Apparently `operands(call::Instruction)` doesn't only include the function type, but also any operand bundle inputs. Because of that, GPUCompiler.jl was incorrectly rewriting some calls as emitted by Julia (notably `ccall`s which encode rooted values using operand bundles). We can't just drop those, since then the alloc optimization pass may do incorrect stuff, so add support to the C API for enumerating and creating calls with operand bundles attached to them.

Add support for inspecting and creating operand bundles.

---

Manifest.toml
Project.toml
deps/LLVMExtra/lib/llvm-api.cpp
deps/build_local.jl
lib/12/libLLVM_h.jl
lib/13/libLLVM_h.jl
lib/libLLVM_extra.jl
src/LLVM.jl

Needs a rebuild of LLVMExtra_jll. Also, the ORCv2 tests fail on LLVM 13 (on macOS at least, didn't test on other platforms) but we can fix that later.

Initial support for LLVM 13.

---

Manifest.toml
src/executionengine/lljit.jl

Fixes https://github.com/maleadt/LLVM.jl/issues/276

Bump LLVMExtra for Julia 1.8 compatibility.

---

src/core/value.jl
src/core/value/constant.jl
src/interop/base.jl
src/utils.jl
test/core.jl

This adds a quick way to get the eltype of a  `PointerType`.

add `llvmeltype`

---

deps/build_local.jl

Without it, the RPATH isn't stripped, and we may end up loading the wrong libLLVM.
Fixes https://github.com/maleadt/LLVM.jl/issues/298

Make sure to install the locally-build LLVMExtra.

---

src/interop/base.jl
test/interop.jl

This PR should update jl_type_to_llvm calls to pass the context along, which is required when JuliaLang/julia#43827 is merged.

Update jl_type_to_llvm to require a context in >= v1.9

---

Manifest.toml
Project.toml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/metadata.jl
test/core.jl

Upstream ValueAsMetadata handles the extraction, MetadataAsValue doesn't: https://github.com/llvm/llvm-project/blob/6c2a01ce3a824622e4491e913023c304841363b1/llvm/lib/IR/Core.cpp#L1157-L1168=

Add support for extracting a Value from a ValueAsMetadata.

---

src/debuginfo.jl

There aren't methods for using these structs, but we currently fail if we don't recognize it. Maybe that's not the best design, but let's just add support using the existing set-up for now.

Support for iterating DICompileUnits in debug info.

---

Manifest.toml
Project.toml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/metadata.jl
src/core/value.jl
test/core.jl

Hack inspired by https://discourse.llvm.org/t/replacing-module-metadata-uses-of-function/62431/4
We should probably remove the type assertion from `ValueAsMetadata::doRAUW` in upstream LLVM.
When we have https://reviews.llvm.org/D125388 we can simplify this.

Add support for replacing values in metadata.

---

src/core/instructions.jl
src/interop.jl
src/interop/atomics.jl
test/atomics.jl
test/instructions.jl
test/runtests.jl

This patch introduces `LLVM.Interop.atomic_pointer*` on `LLVMPtr` mimicking [`Core.Intrinsics.atomic_pointer*` API](https://docs.julialang.org/en/v1.7/base/multi-threading/) on `Ptr`. This is a superset of https://github.com/JuliaGPU/CUDA.jl/pull/1393. It extracts the "CUDA-unaware" part of the atomics previously partially implemented in CUDA.jl. My motivation for this is to implement GPU-interop of https://github.com/JuliaConcurrent/UnsafeAtomics.jl and https://github.com/JuliaConcurrent/Atomix.jl without explicitly dispatching on CUDA.jl and AMDGPU.jl types.
As discussed in https://github.com/JuliaGPU/CUDA.jl/pull/1393 the native code from this is not particularly good on CUDA. But that's probably fixable in LLVM (a long-term solution). As a short-term solution, I think CUDA.jl and …

Add atomic intrinsics

---

src/interop/pointer.jl
test/interop.jl

Base's reinterpret only calls bitcast, which is insufficient when the source and destination pointers have different address spaces.

Add generated Interop.addrspacecast for LLVMPtr

---

Manifest.toml
Project.toml
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/module.jl
src/core/type.jl
src/core/value/constant.jl
test/core.jl

GPUCompiler was relying on an `isa(x::ConstantDataArray, ConstantArray)`, which is wrong, but we can't easily rectify that. So let's merge revert those changes on 4.17 and put them on 5.0 instead.
This means that the next LLVM release will be breaking, which is probably going to be helpful anyway for the opaque pointer migration (so @gbaraldi that gives you some more options in https://github.com/maleadt/LLVM.jl/pull/326).

Revert ConstantArray changes.

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/value.jl
src/core/value/constant.jl
src/interop/base.jl
src/irbuilder.jl
src/utils.jl
test/core.jl
test/instructions.jl
test/utils.jl

This PR removes the (IMO unclear) `llvmtype` function, and replaces it with `value_type` which I think more clearly conveys the meaning, i.e., returning the LLVMType of this object when treated as an LLVM `Value`. It is consistent with other type getters we have, e.g., `function_type` to return the FunctionType when treating this object as an LLVM `Function`, and we might add others later to fetch type information from specific types in the LLVM hierarchy.
(`return_type(::FunctionType)` doesn't fit this scheme, but is clear enough to be its own thing).
Forcing users to replace `llvmtype` with `value_type` or `function_type` should also 'help' with the silent breakage of `eltype(llvmtype(::Function))` (a relatively common pattern) which will be illegal on LLVM 15+ under opaque pointers. …

Rename llvmtype to value_type, remove llvmeltype.

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/type.jl
test/core.jl
test/helpers.jl
test/instructions.jl
test/interop.jl
test/runtests.jl
test/transform.jl

I flushed out some issues by running with `-force-opaque-pointers` (on LLVM 13) and `--opaque-pointers` (on LLVM 15):
- pointer opaqueness is a property of the pointer; it's possible to mix both (`%59 = addrspacecast i32* %4 to ptr addrspace(2)`)
- the context preference isn't static, and may change due to IR upgrade operations (see https://github.com/maleadt/LLVM.jl/issues/336#issuecomment-1481106558)
Sadly we can't test this on CI, as Julia gates support for opaque pointers behind the compile-time `JL_LLVM_OPAQUE_POINTERS` flag, instead of checking the context or input types.
Fixes https://github.com/maleadt/LLVM.jl/issues/336#issuecomment-1481106558

Improve opaque pointer support.

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
examples/Kaleidoscope/codegen.jl
examples/constrained.jl
examples/generated.jl
examples/sum.jl
examples/sum_integrated.jl
examples/sum_orc.jl
lib/libLLVM_extra.jl
src/base.jl
src/core/value/constant.jl
src/deprecated.jl
src/interop.jl
src/interop/asmcall.jl
src/interop/pointer.jl
src/irbuilder.jl
test/analysis.jl
test/bitcode.jl
test/core.jl
test/execution.jl
test/instructions.jl
test/interop.jl
test/ir.jl
test/linker.jl
test/orc.jl
test/orcv2.jl
test/pass.jl
test/targetmachine.jl
test/utils.jl

With https://github.com/maleadt/LLVM.jl/pull/152 introducing `DIBuilder`, we shouldn't have a generically-named `Builder`. Now that we're breaking things, let's rename this to `IRBuilder`.
I did add a deprecation to not make this breaking right away, as well as added deprecations for `llvmtype` and `llvmeltype`; no reason to make this release extra painful.

Refactor in anticipation of breaking release

---

src/interop/pointer.jl

For https://github.com/JuliaGPU/CUDA.jl/pull/1895
Interestingly, we do still get an `i64`. With a simple CUDA `vadd` kernel, the unoptimized LLVM IR is:
```llvm
; PTX CompilerJob of MethodInstance for vadd(::CuDeviceMatrix{Float32, 1, Int32}, ::CuDeviceMatrix{Float32, 1, Int32}, ::CuDeviceMatrix{Float32, 1, Int32}) for sm_86
define ptx_kernel void @_Z4vadd13CuDeviceArrayI7Float32Li2ELi1E5Int32ES_IS0_Li2ELi1ES1_ES_IS0_Li2ELi1ES1_E({ i8 addrspace(1)*, i32, [2 x i32], i32 } %0, { i8 addrspace(1)*, i32, [2 x i32], i32 } %1, { i8 addrspace(1)*, i32, [2 x i32], i32 } %2) local_unnamed_addr #1 {
conversion:
%3 = alloca { i8 addrspace(1)*, i32, [2 x i32], i32 }, align 8
store { i8 addrspace(1)*, i32, [2 x i32], i32 } %0, { i8 addrspace(1)*, i32, [2 x i32], i32 }* %3, align 8
%4 = alloca { i8 …
```

Preserve integer index type for pointerref/pointerset.

---

src/init.jl

This PR adds support for the Colossus backend implemented in [Graphcore's LLVM fork](https://github.com/graphcore/llvm-project-fork).
This backend isn't officially in upstream LLVM, but it should be OK to keep it, if LLVM doesn't know it, it will simply skip it.

Add `Colossus` to list of backends to initialise

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/analysis.jl
test/analysis_tests.jl

This API can be useful, e.g., to discover that an instruction is executed exclusively on a throwing code-path.
cc @gbaraldi

LLVMExtra: Add basic (Post)DominatorTree API

---

deps/build_local.jl
src/interop.jl

Closes https://github.com/maleadt/LLVM.jl/issues/362

Minor changes

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/llvm-api.cpp
lib/libLLVM_extra.jl
src/core/context.jl
src/executionengine/ts_module.jl

Adds an `opaque_pointers` kwarg to the `Context` and `ThreadSafeContext` constructors, while checking that the flag hasn't been set already. This relies on https://github.com/JuliaLang/julia/pull/51840, which makes it so that Julia doesn't default to setting this flag (preventing us from changing the setting).

Improve API for setting pointer mode

---

test/interop_tests.jl
test/runtests.jl

Adapts to https://github.com/JuliaLang/julia/pull/51720

Adapt opaque pointer determination for LLVM 16.

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/Core.cpp
lib/13/libLLVM_extra.jl
lib/14/libLLVM_extra.jl
lib/15/libLLVM_extra.jl
lib/16/libLLVM_extra.jl
src/core/instructions.jl
test/instructions_tests.jl

As requested by @chriselrod
Backport llvm/llvm-project#75123 to LLVMExtra, and add a Julian API:
- `fast_math(::Instruction)` returning a named tuple
- `fast_math!(::Instruction; flags...)` specifying flags as kwargs as kwarg
I contemplated using symbols instead (`fast_math!(inst, :contract)`), but with kwargs its easier to pass multiple flags.

Add support for setting and querying fast math flags.

---

src/interop/pointer.jl
test/interop_tests.jl

Fixes https://github.com/maleadt/LLVM.jl/issues/386, towards fixing https://github.com/JuliaGPU/Metal.jl/issues/282

LLVMPtr: Implement arithmetic without using Base.add_ptr to avoid addrspacecasts

---

Project.toml

Not sure why CompatHelper.jl didn't do this...
@DilumAluthge do you know? LLVM.jl had the following BFloat16s.jl-related entries in Project.toml: https://github.com/maleadt/LLVM.jl/blob/5a34b05e1797b9fd6b4254d91874bd7e8816a20b/Project.toml#L14-L21
BFloat16s.jl 0.5 has been released for a while, yet CompatHelper.jl on here doesn't even mention the package in its logs: https://github.com/maleadt/LLVM.jl/actions/runs/8547271848/job/23419132957. We are using the latest CompatHelper.jl, v3.10.0.

Update Bfloat16s.jl compat bound.

---

examples/Kaleidoscope/run.jl
src/LLVM.jl
src/core/value/constant.jl
src/init.jl
src/newpm/passes.jl
test/essential_tests.jl
test/runtests.jl

Remaining issue: ORC is broken on LLVM 17
```
❯ jl +nightly --project examples/sum_orc.jl
ERROR: LoadError: LLVM error: Symbols not found: [ llvm_orc_registerEHFrameSectionWrapper ]
Stacktrace:
[1] macro expansion
@ ~/Julia/pkg/LLVM/src/executionengine/utils.jl:32 [inlined]
[2] LLJIT(builder::LLJITBuilder)
@ LLVM ~/Julia/pkg/LLVM/src/executionengine/lljit.jl:38
[3] #LLJIT#66
@ ~/Julia/pkg/LLVM/src/executionengine/lljit.jl:59 [inlined]
[4] top-level scope
@ ~/Julia/pkg/LLVM/examples/sum_orc.jl:45
[5] include
@ ./Base.jl:559 [inlined]
[6] exec_options(opts::Base.JLOptions)
@ Base ./client.jl:325
[7] _start()
@ Base ./client.jl:533
in expression starting at /home/tim/Julia/pkg/LLVM/examples/sum_orc.jl:45
```
Looks like ORC now expects certain LLVM symbols to be globally visible: …

LLVM 17 enablement.

---

src/interop/newpm.jl
test/newpm_tests.jl

Adopts to JuliaLang/julia#51883 
@maleadt I am unsure what kind of version bump this warrants.

LowerSIMDLoopPass is a Loop Pass in 1.10

---

src/newpm/passes.jl

Requires https://github.com/llvm/llvm-project/pull/92383, which was back-ported to LLVM 17 in https://github.com/JuliaPackaging/Yggdrasil/pull/8697 and landed in Julia in https://github.com/JuliaLang/julia/pull/54515.

Support NewPM internalize pass options.

---

src/newpm/utilities.jl

Plain `@error` isn't allowed in compilation context.

Safely report custom pass errors.

---

src/newpm.jl

Otherwise, when submitting an empty pass manager (see e.g. https://github.com/JuliaGPU/GPUCompiler.jl/commit/6c3c8f67c642f19fefdcb1443c4e1b34668a97b0 for a real-life example) you get an inscrutable error (`LLVM ERROR: Unknown function pass ''`).

NewPM: Warn early when using invalid empty pass lists.

---

deps/LLVMExtra/CMakeLists.txt
deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/NewPM.cpp
lib/15/libLLVM_extra.jl
lib/16/libLLVM_extra.jl
lib/17/libLLVM_extra.jl
lib/18/libLLVM_extra.jl
src/newpm.jl
test/Project.toml
test/newpm_tests.jl

Example:
```julia
@dispose ctx=Context() pb=NewPMPassBuilder() begin
@dispose pb=NewPMPassBuilder(;debug_logging=true) mod=test_module() begin
add!(pb, NewPMAAManager()) do aa
add!(aa, "basic-aa")
end
add!(pb, "aa-eval")
@test run!(pb, mod) === nothing
end
end
```
Fixes https://github.com/maleadt/LLVM.jl/issues/436
x-ref https://discourse.llvm.org/t/newpm-c-api-questions/80598

Add support for specifying the AA pipeline.

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/NewPM.cpp
lib/15/libLLVM_extra.jl
lib/16/libLLVM_extra.jl
lib/17/libLLVM_extra.jl
lib/18/libLLVM_extra.jl
src/newpm.jl
test/newpm_tests.jl

Fixes https://github.com/maleadt/LLVM.jl/issues/435
Draft until accepted upstream: https://github.com/llvm/llvm-project/pull/103773

Add the ability to run passes on a single function.

---

deps/LLVMExtra/include/LLVMExtra.h
deps/LLVMExtra/lib/Core.cpp
lib/15/libLLVM_extra.jl
lib/16/libLLVM_extra.jl
lib/17/libLLVM_extra.jl
lib/18/libLLVM_extra.jl
src/core/instructions.jl
src/deprecated.jl
src/irbuilder.jl
test/instructions_tests.jl

Switches to https://github.com/llvm/llvm-project/pull/104775
@pxl-th This deprecates your previous implementation, now using explicit `SyncScope("agent")` ctors instead of keeping everything string-based. Thoughts?

Switch the syncscope implementation to the upstream one.

---

src/irbuilder.jl
test/instructions_tests.jl

Used by GPUCompiler.jl: https://github.com/JuliaGPU/GPUCompiler.jl/blob/b71344189c86531cb61fe630cf512b3a0b6558a8/src/metal.jl#L533-L535

Add back a convenience function for calling with operand bundles.

---

src/core/basicblock.jl
src/core/function.jl
src/core/instructions.jl
src/core/metadata.jl
src/core/module.jl
test/core_tests.jl
test/execution_tests.jl
test/newpm_tests.jl

This PR exposes functionality to move to the previous/next instruction/block/function by means of `prevXXX`/`nextXXX` functions (inspired by `prevfloat`/`nextfloat` and `prevind`/`nextind`). Not particularly idiomatic, but I couldn't immediately find another common iterator abstraction to implement this kind of operation...

Extend iteration interface

---

src/core/basicblock.jl
src/core/instructions.jl
src/core/type.jl
src/deprecated.jl
test/core_tests.jl

- tighten some functions to avoid assertions
- return human-readable ints from length etc methods
- switch from size to length for vector types.

NFC clean-ups.

---

src/core/metadata.jl
src/core/module.jl
src/core/type.jl
src/core/value.jl

LLVM's string representations often contain superfluous whitespace, which doesn't look nice in the REPL.
I originally wanted to do this in the `string` functions, but returning a `SubString` from there is unexpected and breaks things (such as the `llvmcall` embedding). Flattening to a String would incur copies everywhere, and doing pointer magic in `unsafe_message` can only skip leading whitespace without scanning the buffer twice for the terminating null.
So let's keep things simple and only strip when displaying.

Strip whitespace when showing LLVM objects.

---

src/LLVM.jl
src/init.jl
src/passregistry.jl
test/essential_tests.jl
test/support_tests.jl

They are unused, unneeded, and removed from LLVM 17+.

Remove PassRegistry wrappers.

---

src/core/context.jl

It's an internal type that's only used in the installed handlers.

Unexport DiagnosticInfo.

---

src/LLVM.jl
src/core/context.jl
test/core_tests.jl

Has been removed from upstream for ages: https://reviews.llvm.org/D19094

Remove support for global contexts.

---

src/interop/passes.jl
test/interop_tests.jl
test/newpm_tests.jl

This is a companion PR to https://github.com/JuliaLang/julia/pull/55407 so it probably won't pass tests just yet. That PR will also get backported to 1.11 so unfortunately the version checks will get a bit messy.

Add API for the new parsing options to JuliaPipelinePassOptions

---

src/core/instructions.jl
src/core/module.jl
src/deprecated.jl

Copy-constructors aren't a common thing in Julia (even in Base some are no-ops, others copy), so let's be explicit.

Deprecate copy ctors in favor of Base.copy.

---

src/core/basicblock.jl
src/core/function.jl
src/core/instructions.jl
src/core/value/constant.jl
src/deprecated.jl
test/core_tests.jl

These functions also don't have to take a `parent` argument, as `Base.delete!` does, making them more general (e.g., to erase unlinked instructions or blocks).

Replace (unsafe_)delete! with remove!/erase!, closer to upstream.

---

src/core/metadata.jl
src/deprecated.jl
test/core_tests.jl

`string` methods are supposed to mimic printing to I/O, while here we're extracting the underlying string (`!{"foo"}` vs `"foo"`). It was also silly to have this behave differently with different Metadata subtypes.

MDString: deprecate string in favor of convert.

---

src/executionengine/ts_module.jl
test/orc_tests.jl

In https://github.com/maleadt/LLVM.jl/pull/459, I added a simple assertion to make sure the module passed to `LLVMOrcCreateNewThreadSafeModule` resides in the same context as the thread-safe context passed to the API, because the `ThreadSafeModule` ctor called by the C API simply creates a new object without copying:
- https://github.com/llvm/llvm-project/blob/36c210bb340cfdc68d314dd188e18c0bf017b999/llvm/lib/ExecutionEngine/Orc/OrcV2CBindings.cpp#L748-L753
- https://llvm.org/doxygen/classllvm_1_1orc_1_1ThreadSafeModule.html#aad76bc6379e9faa0a0b2e360817bbc37
This tripped up Enzyme:
```
ABI & Calling convention: Error During Test at /home/runner/work/LLVM.jl/LLVM.jl/downstream/test/abi.jl:4
Got exception outside of a @test
AssertionError: context(mod) == context(ts_context())
Stacktrace: …
```

Fix constructing a ThreadSafeModule from a Module in a different Ctx.

---

src/core/metadata.jl

AFAIU only MDNodes are allowed: https://github.com/llvm/llvm-project/blob/d21e731c42d6b967e29dbe2edc16c1b86885df0d/llvm/lib/IR/Core.cpp#L1091-L1092
Before:
```
julia> metadata(inst)["foo"] = MDString("bar");
julia: /workspace/srcdir/llvm-project/llvm/lib/IR/Core.cpp:940: llvm::MDNode* extractMDNode(llvm::MetadataAsValue*): Assertion `(isa<MDNode>(MD) || isa<ConstantAsMetadata>(MD)) && "Expected a metadata node or a canonicalized constant"' failed.
```
After:
```
julia> metadata(inst)["foo"] = MDString("bar");
ERROR: MethodError: no method matching setindex!(::LLVM.InstructionMetadataDict, ::MDString, ::String)
Closest candidates are:
setindex!(::AbstractDict, ::Any, ::Any, ::Any, ::Any...)
@ Base abstractdict.jl:550
setindex!(::LLVM.InstructionMetadataDict, ::MDNode, ::Any)
@ LLVM …
```

Restrict SetMetadata to MDNodes.

---

src/core/value/constant.jl
src/irbuilder.jl
test/instructions_tests.jl

This isn't exposed by the C API, and I figured reimplementing it is easier than doing the LLVMExtra+upstreaming dance.

Reimplement globalstring to provide addrspace control.

---

Project.toml
src/core/instructions.jl

Wasn't exported before; clashes with `Base.parent`. Maybe we should just re-use the latter, but let's do the quick fix for now.

Unexport 'parent'.

---

src/debug.jl
src/executionengine/ts_module.jl

This should be NFC, but lets see if CI still fails.

Fix TSModule tracking.

---

Project.toml
lib/19/libLLVM.jl
lib/19/libLLVM_extra.jl
src/LLVM.jl
src/core/metadata.jl
src/core/value/constant.jl
src/newpm.jl
test/core_tests.jl
test/debuginfo_tests.jl

See below for the difference from 18.
AFAICT, the only breaking change that's used in this repo is the removal of fcmp, icmp and shl constant expressions.
<details>
<summary>Difference between 18 and 19</summary>
```diff
diff -u 18/libLLVM.jl 19/libLLVM.jl
--- 18/libLLVM.jl	2025-01-21 09:44:18.425196908 -0500
+++ 19/libLLVM.jl	2025-01-21 09:44:18.425196908 -0500
@@ -83,6 +83,8 @@
mutable struct LLVMOpaqueBinary end
+mutable struct LLVMOpaqueDbgRecord end
+
mutable struct LLVMOpaqueTargetData end
mutable struct LLVMOpaqueTargetLibraryInfotData end
@@ -659,6 +661,7 @@
LLVMInstructionValueKind = 24
LLVMPoisonValueValueKind = 25
LLVMConstantTargetNoneValueKind = 26
+    LLVMConstantPtrAuthValueKind = 27
end
"""
@@ -778,23 +781,25 @@
"""
LLVMAtomicRMWBinOp
-| Enumerator             | Note …
```

Generate julia wrappers for LLVM19

---

docs/src/lib/values.md
docs/src/man/values.md
src/core/value/constant.jl
test/core_tests.jl

Same as `unnamed_addr/unnamed_addr!`.
Also changed implementation of `unnamed_addr` to use `LLVM.GetUnnamedAddress`, because `LLVM.HasUnnamedAddr` is deprecated.

Add `local_unnamed_addr/local_unnamed_addr!` functions

---

docs/src/lib/functions.md
docs/src/lib/instructions.md
docs/src/man/instructions.md
src/core/instructions.jl
test/core_tests.jl

Implementation is similar to that of function attributes, using a new `CallSiteAttrSet` and the bindings listed here https://llvm.org/doxygen/group__LLVMCCoreValueInstructionCall.html#details.

Implement attribute iterators for call sites and invocations
